/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PkgPresentacion;

import PkgEntidad.ClsApoderado;
import PkgEntidad.ClsEquipo;
import PkgEntidad.ClsPartidoTenisMesa;
import PkgNegocios.ClsMetodoEquipo;
import PkgNegocios.ClsMetodosVariados;
import PkgNegocios.ClsTenisMesa;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author proxc
 */
public final class FrmTenisMesa extends javax.swing.JFrame{
    
    int[][] datos;
    ClsMetodosVariados metodosVariados = new ClsMetodosVariados();
    List<ClsEquipo> equipos;
    ClsEquipo equipo;
    ClsTenisMesa clstenisMesa = new ClsTenisMesa();
    ClsMetodoEquipo metodoEquipo;
    List<ClsApoderado> participante = new ArrayList<>();    
    int lugar1 = 0, lugar2 = 0;
    int limEquipo = 2;
    int set = 0;
    int steq1=0,steq2=0;
    ArrayList<ClsApoderado> jugador = new ArrayList<>();
    ClsApoderado jugador1,jugador2,jugador3,jugador4; // CAMBIANDO FORMA DE COLOCAR JUGADORES POR LINEA DE ARRIBA
    
    /**
     * Creates new form Home_Data
     */
    public FrmTenisMesa() {
        initComponents();
        cmbSerie.setEnabled(true);
        BloquearControles();
        MtdSerie();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtArbitro = new javax.swing.JTextField();
        cmbSerie = new javax.swing.JComboBox<>();
        cmbNroPartido = new javax.swing.JComboBox<>();
        LblCarga1 = new java.awt.Label();
        LblCarga2 = new java.awt.Label();
        LblIdDisciplina = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblSET = new javax.swing.JLabel();
        btnValidarEquipo2 = new javax.swing.JButton();
        btnValidarEquipo1 = new javax.swing.JButton();
        LblP12 = new javax.swing.JLabel();
        LblP11 = new javax.swing.JLabel();
        LblP22 = new javax.swing.JLabel();
        LblP21 = new javax.swing.JLabel();
        lblPE1 = new javax.swing.JLabel();
        lblPE2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtP1E1 = new javax.swing.JTextField();
        txtP1E2 = new javax.swing.JTextField();
        txtP2E1 = new javax.swing.JTextField();
        txtP2E2 = new javax.swing.JTextField();
        txtP3E1 = new javax.swing.JTextField();
        txtP3E2 = new javax.swing.JTextField();
        BtnIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstEquipoLocal = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LstEquipoVisita = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tenis-de-mesa.png"))); // NOI18N
        jLabel15.setText("Tenis de Mesa");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 40, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Serie:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("N° de Partido:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Arbitro:");

        cmbSerie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar opcion" }));
        cmbSerie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSerieItemStateChanged(evt);
            }
        });
        cmbSerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbSerieMouseReleased(evt);
            }
        });
        cmbSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSerieActionPerformed(evt);
            }
        });

        cmbNroPartido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar opcion" }));
        cmbNroPartido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNroPartidoItemStateChanged(evt);
            }
        });

        LblCarga1.setText("label1");

        LblCarga2.setText("label1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbNroPartido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArbitro)
                    .addComponent(cmbSerie, 0, 175, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cmbNroPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 11, -1, -1));
        jPanel1.add(LblIdDisciplina, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 116, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel7.setText("SET:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lblSET.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        lblSET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cronografo.png"))); // NOI18N
        lblSET.setText("1");
        jPanel2.add(lblSET, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        btnValidarEquipo2.setText("2do Equipo");
        btnValidarEquipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarEquipo2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnValidarEquipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 113, 37));

        btnValidarEquipo1.setText("1er Equipo");
        btnValidarEquipo1.setBorder(null);
        btnValidarEquipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarEquipo1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnValidarEquipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 113, 37));

        LblP12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/camiseta-de-futbol-local.png"))); // NOI18N
        jPanel2.add(LblP12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 44));

        LblP11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/camiseta-de-futbol-local.png"))); // NOI18N
        jPanel2.add(LblP11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 44));

        LblP22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/camiseta-de-futbol-visita.png"))); // NOI18N
        jPanel2.add(LblP22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 44));

        LblP21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/camiseta-de-futbol-visita.png"))); // NOI18N
        jPanel2.add(LblP21, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, 44));

        lblPE1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPE1.setText("0");
        lblPE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 54, 94));

        lblPE2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPE2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPE2.setText("0");
        lblPE2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblPE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 54, 94));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        jLabel11.setText("Equipo 1:");

        jLabel13.setFont(new java.awt.Font("Verdana", 2, 12)); // NOI18N
        jLabel13.setText("Equipo 2:");

        txtP1E1.setBackground(new java.awt.Color(204, 204, 204));
        txtP1E1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtP1E1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP1E1.setText("0");

        txtP1E2.setBackground(new java.awt.Color(204, 204, 204));
        txtP1E2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtP1E2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP1E2.setText("0");

        txtP2E1.setBackground(new java.awt.Color(204, 204, 204));
        txtP2E1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtP2E1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP2E1.setText("0");

        txtP2E2.setBackground(new java.awt.Color(204, 204, 204));
        txtP2E2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtP2E2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP2E2.setText("0");
        txtP2E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2E2ActionPerformed(evt);
            }
        });

        txtP3E1.setBackground(new java.awt.Color(204, 204, 204));
        txtP3E1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtP3E1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP3E1.setText("0");

        txtP3E2.setBackground(new java.awt.Color(204, 204, 204));
        txtP3E2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtP3E2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtP3E2.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtP1E2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP2E2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtP1E1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP2E1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtP3E1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtP3E2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtP3E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtP3E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtP1E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtP2E1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtP1E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtP2E2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 281, -1));

        BtnIniciar.setText("INICIAR PARTIDO");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });
        jPanel2.add(BtnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 224, 37));

        jScrollPane1.setViewportView(LstEquipoLocal);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 165));

        jScrollPane2.setViewportView(LstEquipoVisita);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 11, 270, 165));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSerieMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSerieMouseReleased
        
    }//GEN-LAST:event_cmbSerieMouseReleased

    private void cmbSerieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSerieItemStateChanged
        if(cmbSerie.getItemAt(0).equals("Seleccionar opcion")){
            cmbNroPartido.removeAllItems();
            cmbNroPartido.addItem("Seleccionar opcion");
            cmbNroPartido.setEnabled(false);
        }
        try {
            LblCarga1.setText(String.valueOf(metodosVariados.listaSerie().get(cmbSerie.getSelectedIndex()-1).getIdSerie()));
            MtdPartido();
        } catch (SQLException ex) {
            Logger.getLogger(FrmTenisMesa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbSerieItemStateChanged

    private void cmbSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSerieActionPerformed
    }//GEN-LAST:event_cmbSerieActionPerformed

    private void cmbNroPartidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNroPartidoItemStateChanged
        if(cmbNroPartido.getSelectedIndex()!=0 && cmbNroPartido.getItemCount()>0){
            LblCarga2.setText(cmbNroPartido.getSelectedItem().toString());
            txtArbitro.setEnabled(true);
            try {
                MtdEquipos();
            } catch (SQLException ex) {
                Logger.getLogger(FrmTenisMesa.class.getName()).log(Level.SEVERE, null, ex);
            }
            btnValidarEquipo1.setText("<html><center><b>"+equipos.get(0).getNombreEquipo()+"</b><br>"+equipos.get(0).getDetalleEquipo()+"</center></html>");
            btnValidarEquipo2.setText("<html><center><b>"+equipos.get(1).getNombreEquipo()+"</b><br>"+equipos.get(1).getDetalleEquipo()+"</center></html>");
            BtnIniciar.setText("Bloquear Equipos");
            LstEquipoLocal.setEnabled(true);
            LstEquipoVisita.setEnabled(true);
            BtnIniciar.setEnabled(true);
            try {
                MtdCargarListasEquipo();
            } catch (SQLException ex) {
                Logger.getLogger(FrmTenisMesa.class.getName()).log(Level.SEVERE, null, ex);
            }
                /*
                btnValidarEquipo1.setEnabled(true);
                btnValidarEquipo2.setEnabled(true);*/
        }
    }//GEN-LAST:event_cmbNroPartidoItemStateChanged

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        if(BtnIniciar.getText().equals("FINALIZAR")){
            
            
            
            
            clstenisMesa.guardarPartido(datos, 0);
        }    
        set = 1;
        BtnIniciar.setEnabled(false);
        btnValidarEquipo1.setEnabled(true);
        btnValidarEquipo2.setEnabled(true);
        cmbNroPartido.setEnabled(false);
        cmbSerie.setEnabled(false);
    }//GEN-LAST:event_BtnIniciarActionPerformed

    private void btnValidarEquipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarEquipo1ActionPerformed
        int eq1 = Integer.parseInt(lblPE1.getText());
        eq1++;
        lblPE1.setText(String.valueOf(eq1));
        if(eq1 == 11){
            switch (set) {
                case 1:
                    txtP1E1.setText(String.valueOf(eq1));
                    txtP1E1.setForeground(Color.blue);
                    txtP1E2.setText(lblPE2.getText());
                    txtP1E2.setForeground(Color.red);
                    steq1++;
                    set++;
                    lblSET.setText("2");        
                    break;
                case 2:
                    txtP2E1.setText(String.valueOf(eq1));
                    txtP2E1.setForeground(Color.blue);
                    txtP2E2.setText(lblPE2.getText());
                    txtP2E2.setForeground(Color.red);
                    steq1++;
                    set++;
                    lblSET.setText("3");
                    break;
                case 3:
                    txtP3E1.setText(String.valueOf(eq1));
                    txtP3E1.setForeground(Color.blue);
                    txtP3E2.setText(lblPE2.getText());
                    txtP3E2.setForeground(Color.red);
                    steq1++;
                    break;
            }
            lblPE1.setText("0");
            lblPE2.setText("0");
        }
        MtdVerificar();
    }//GEN-LAST:event_btnValidarEquipo1ActionPerformed

    private void btnValidarEquipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarEquipo2ActionPerformed
        int eq2 = Integer.parseInt(lblPE2.getText());
        eq2++;
        lblPE2.setText(String.valueOf(eq2));
        if(eq2 == 11){
            switch (set) {
                case 1:
                    txtP1E1.setText(lblPE1.getText());
                    txtP1E1.setForeground(Color.red);
                    txtP1E2.setText(String.valueOf(eq2));
                    txtP1E2.setForeground(Color.blue);
                    steq2++;
                    set++;
                    lblSET.setText("2");
                    break;
                case 2:
                    txtP2E1.setText(lblPE1.getText());
                    txtP2E1.setForeground(Color.red);
                    txtP2E2.setText(String.valueOf(eq2));
                    txtP2E2.setForeground(Color.BLUE);
                    steq2++;
                    set++;
                    lblSET.setText("3");
                    break;
                case 3:
                    txtP3E1.setText(lblPE1.getText());
                    txtP3E1.setForeground(Color.red);
                    txtP3E2.setText(String.valueOf(eq2));
                    txtP3E2.setForeground(Color.blue);
                    steq2++;
                    break;
            }
            lblPE1.setText("0");
            lblPE2.setText("0");
        }
        MtdVerificar();
    }//GEN-LAST:event_btnValidarEquipo2ActionPerformed

    private void txtP2E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2E2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2E2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTenisMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTenisMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTenisMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTenisMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }
    
    
    // BLOQUEAR COMPONENTES
    
    public void BloquearControles(){
        cmbNroPartido.setEnabled(false);
        LstEquipoLocal.setEnabled(false);
        LstEquipoVisita.setEnabled(false);
        LstEquipoLocal.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent evt) {
            JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) {
                    // Double-click detectado
                    // EQUIPO 1
                    // OBTENER DNI
                    String[] partes = String.valueOf(list.getSelectedValue()).split(" ");
                    String  dni = partes[0];
                    
                    if(lugar1 < 3){
                        for(int i = 0; i < participante.size(); i++){
                            if(dni.equals(participante.get(i).getDni())){
                                if(lugar1 == 0){
                                    jugador1 = participante.get(i);
                                    LblP11.setText(jugador1.getNombres() + " " + jugador1.getApePaterno() + " " + jugador1.getApeMaterno());
                                    lugar1++;
                                    break;
                                }else if(lugar1 == 1){
                                    jugador2 = participante.get(i);
                                    LblP12.setText(jugador2.getNombres() + " " + jugador2.getApePaterno() + " " + jugador2.getApeMaterno());
                                    lugar1--;
                                    break;
                                }

                            }
                        } 
                    }
                }
            }
        });
        LstEquipoVisita.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent evt) {
            JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) {
                    // Double-click detectado
                    // EQUIPO 2
                    // OBTENER DNI
                    String[] partes = String.valueOf(list.getSelectedValue()).split(" ");
                    String  dni = partes[0];
                    
                    if(lugar1 < 3){
                        for(int i = 0; i < participante.size(); i++){
                            if(dni.equals(participante.get(i).getDni())){
                                if(lugar1 == 0){
                                    jugador1 = participante.get(i);
                                    LblP21.setText(jugador1.getNombres() + " " + jugador1.getApePaterno() + " " + jugador1.getApeMaterno());
                                    lugar1++;
                                    break;
                                }else if(lugar1 == 1){
                                    jugador2 = participante.get(i);
                                    LblP22.setText(jugador2.getNombres() + " " + jugador2.getApePaterno() + " " + jugador2.getApeMaterno());
                                    lugar1--;
                                    break;
                                }

                            }
                        } 
                    }
                }
            }
        });
        txtArbitro.setEnabled(false);
        txtP1E1.setEditable(false);
        txtP2E1.setEditable(false);
        txtP3E1.setEditable(false);
        
        txtP1E2.setEditable(false);
        txtP2E2.setEditable(false);
        txtP3E2.setEditable(false);
        
        btnValidarEquipo1.setEnabled(false);
        btnValidarEquipo2.setEnabled(false);
        BtnIniciar.setEnabled(false);
        
        LblCarga1.setVisible(false);
        LblCarga2.setVisible(false);
        LblIdDisciplina.setEnabled(false);
        LblIdDisciplina.setText("2");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private java.awt.Label LblCarga1;
    private java.awt.Label LblCarga2;
    private javax.swing.JLabel LblIdDisciplina;
    private javax.swing.JLabel LblP11;
    private javax.swing.JLabel LblP12;
    private javax.swing.JLabel LblP21;
    private javax.swing.JLabel LblP22;
    private javax.swing.JList<String> LstEquipoLocal;
    private javax.swing.JList<String> LstEquipoVisita;
    private javax.swing.JButton btnValidarEquipo1;
    private javax.swing.JButton btnValidarEquipo2;
    private javax.swing.JComboBox<String> cmbNroPartido;
    private javax.swing.JComboBox<String> cmbSerie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPE1;
    private javax.swing.JLabel lblPE2;
    private javax.swing.JLabel lblSET;
    private javax.swing.JTextField txtArbitro;
    private javax.swing.JTextField txtP1E1;
    private javax.swing.JTextField txtP1E2;
    private javax.swing.JTextField txtP2E1;
    private javax.swing.JTextField txtP2E2;
    private javax.swing.JTextField txtP3E1;
    private javax.swing.JTextField txtP3E2;
    // End of variables declaration//GEN-END:variables

    // METODOS DE CARGA
    
    public void MtdSerie(){
        try{
            for(int i = 0; i < metodosVariados.listaSerie().size(); i++){
                cmbSerie.addItem(metodosVariados.listaSerie().get(i).getDescripcionSerie());
            }
        }catch(SQLException e){
            Logger.getLogger(FrmTenisMesa.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    public void MtdPartido(){
        cmbNroPartido.removeAllItems();
        cmbNroPartido.addItem("Seleccionar opcion");
        try{
            for(int i = 0; i < clstenisMesa.listaPartidos(Integer.parseInt(LblCarga1.getText())).size(); i++){
                cmbNroPartido.addItem(String.valueOf(clstenisMesa.listaPartidos(Integer.parseInt(LblCarga1.getText())).get(i).getIdPartidoTenisMesa()));
            }
            cmbNroPartido.setEnabled(true);
        }catch(NumberFormatException | SQLException e){ }        
    }
    
    public void MtdEquipos() throws SQLException{
        equipos = new ArrayList<>();
        ClsPartidoTenisMesa ptenismesa = new ClsPartidoTenisMesa();
        ptenismesa = clstenisMesa.partidoTenisMesa(Integer.parseInt(LblCarga2.getText()));
        metodoEquipo = new ClsMetodoEquipo();
        equipos.add(metodoEquipo.Equipo(ptenismesa.getIdEquipoLocal()));
        equipos.add(metodoEquipo.Equipo(ptenismesa.getIdEquipoVisitante()));
    }
    
    private void MtdCargarListasEquipo() throws SQLException {
        participante.clear();
        for(int i = 0; i < equipos.size(); i++) {
            participante.addAll(metodoEquipo.listaParticipantesEquipo(Integer.parseInt(LblIdDisciplina.getText()),equipos.get(i).getIdAnio()));
        }
        DefaultListModel lista1 = new DefaultListModel(),lista2 = new DefaultListModel();
        for(int i = 0; i < participante.size(); i++){
            if(participante.get(i).getIdAnio() == equipos.get(0).getIdAnio()){
                lista1.addElement(participante.get(i).getDni() + " " + participante.get(i).getNombres() + " " + participante.get(i).getApePaterno());
            }else{
                lista2.addElement(participante.get(i).getDni() + " " + participante.get(i).getNombres() + " " + participante.get(i).getApePaterno());
            }
        }
        LstEquipoLocal.setModel(lista1);
        LstEquipoVisita.setModel(lista2);
        LstEquipoLocal.setSelectionMode(0);
        LstEquipoVisita.setSelectionMode(0);    
    }    

    private void MtdVerificar() {
        int aa,ab;
        int ba,bb;
        
        aa = Integer.parseInt(txtP1E1.getText());
        ab = Integer.parseInt(txtP2E1.getText());
        ba = Integer.parseInt(txtP1E2.getText());
        bb = Integer.parseInt(txtP2E2.getText());
        
        if( aa > ba && ab > bb){
            JOptionPane.showMessageDialog(rootPane, "GANADOR DEL PARTIDO EQUIPO " + equipos.get(0).getNombreEquipo());
            btnValidarEquipo1.setEnabled(false);
            btnValidarEquipo2.setEnabled(false);
            datos = new int[2][5];
            datos[0][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[0][1] = 1;
            datos[0][2] = Integer.parseInt(txtP1E1.getText());
            datos[0][3] = Integer.parseInt(txtP1E2.getText());
            datos[0][4] = equipos.get(0).getIdEquipo();
            datos[1][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[1][1] = 2;
            datos[1][2] = Integer.parseInt(txtP2E1.getText());
            datos[1][3] = Integer.parseInt(txtP2E2.getText());
            datos[1][4] = equipos.get(0).getIdEquipo();        
            BtnIniciar.setText("FINALIZAR");
            BtnIniciar.setEnabled(true);
        }else if(ba > aa && bb > ab){
            JOptionPane.showMessageDialog(rootPane, "GANADOR DEL PARTIDO EQUIPO " + equipos.get(1).getNombreEquipo());
            btnValidarEquipo1.setEnabled(false);
            btnValidarEquipo2.setEnabled(false);
            datos = new int[2][5];
            datos[0][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[0][1] = 1;
            datos[0][2] = Integer.parseInt(txtP1E1.getText());
            datos[0][3] = Integer.parseInt(txtP1E2.getText());
            datos[0][4] = equipos.get(1).getIdEquipo();
            datos[1][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[1][1] = 2;
            datos[1][2] = Integer.parseInt(txtP2E1.getText());
            datos[1][3] = Integer.parseInt(txtP2E2.getText());
            datos[1][4] = equipos.get(1).getIdEquipo();    
            BtnIniciar.setText("FINALIZAR");
            BtnIniciar.setEnabled(true);
        }
        
        if(steq1 == 2){
            btnValidarEquipo1.setEnabled(false);
            btnValidarEquipo2.setEnabled(false);
            datos = new int[3][5];
            datos[0][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[0][1] = 1;
            datos[0][2] = Integer.parseInt(txtP1E1.getText());
            datos[0][3] = Integer.parseInt(txtP1E2.getText());
            if(datos[0][2] > datos[0][3]){
                datos[0][4] = equipos.get(0).getIdEquipo();
            }else{
                datos[0][4] = equipos.get(1).getIdEquipo();
            }
            datos[1][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[1][1] = 2;
            datos[1][2] = Integer.parseInt(txtP2E1.getText());
            datos[1][3] = Integer.parseInt(txtP2E2.getText());
            if(datos[1][2] > datos[1][3]){
                datos[1][4] = equipos.get(0).getIdEquipo();
            }else{
                datos[1][4] = equipos.get(1).getIdEquipo();
            }
            datos[2][0] = Integer.parseInt(cmbNroPartido.getSelectedItem().toString());
            datos[2][1] = 3;
            datos[2][2] = Integer.parseInt(txtP2E1.getText());
            datos[2][3] = Integer.parseInt(txtP2E2.getText());
            if(datos[2][2] > datos[0][3]){
                datos[2][4] = equipos.get(0).getIdEquipo();
            }else{
                datos[2][4] = equipos.get(1).getIdEquipo();
            }
            BtnIniciar.setText("FINALIZAR");
            BtnIniciar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANADOR DEL PARTIDO EQUIPO " + equipos.get(0).getNombreEquipo());
        }else if(steq2 == 2){
            btnValidarEquipo1.setEnabled(false);
            btnValidarEquipo2.setEnabled(false);
            BtnIniciar.setText("FINALIZAR");
            BtnIniciar.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "GANADOR DEL PARTIDO EQUIPO " + equipos.get(1).getNombreEquipo());
        }
        
    }
}
